#
# @Author: wjm
# @Date: 2019-10-13 21:45:10
# @LastEditTime: 2019-10-13 21:46:06
# @Description: file content
# 

name: mff_sfigf_in1_grad1
algorithm: mff_sfigf #HAPNN #arfnet #ugcn_s4nba0
nEpochs: 3000
gpu_mode: True
save_best: True
gpus: [3]
threads: 16  #num_works
log_dir: /home/amax/Documents/yxxxl/pansharpening/results/log/


seed: 123
checkpoint: /home/amax/Documents/yxxxl/pansharpening/results/checkpoint/mff_sfigf_in1_grad1/
data_dir_train: /home/amax/Documents/yxxxl/oridata/RealMFF
data_dir_eval: /home/amax/Documents/yxxxl/oridata/RealMFF
source_ms: ms
source_pan: pan

pretrain:
  pretrained: False
  pre_sr: GPPNN3_4_1647496009/best_900.pth
  pre_folder: /home/kemove/keyu/newpan/checkpoint/gppnn3pami/

test:  #用于指标测试的代码
  algorithm: mff_sfigf #arfnet
  type: test #[test, eval]
  data_dir: /home/amax/Documents/yxxxl/oridata/RealMFF
  source_ms: ms
  source_pan: pan
  model: /home/amax/Documents/yxxxl/pansharpening/results/checkpoint/mff_sfigf_in1_grad1/mff_sfigf_Real-MFF_1721810069/best.pth #pannetnipsi_4_1653126019/latest.pth #arfnet_4_1652535888/best.pth  # no softmax latest  best
  # model: GPPNN3_4_1647436525/latest.pth   #softmax
  save_dir: /home/amax/Documents/yxxxl/pansharpening/results/test/Real-MFF/mff_sfigf_in1_grad1/
data:
  upsacle:  4
  batch_size: 4 #4
  patch_size: 128
  data_augmentation: False                                                                                                                                                                                               
  n_colors: 3
  rgb_range: 255
  normalize : False
  img_scale: 2047.0
  num: 650
  name: Real-MFF # Real-MFF | MFF-WHU
  
schedule:
  lr: 8e-4
  decay1: 1700
  decay2: 1900
  decay3: 2400
  gamma: 0.5
  optimizer: ADAM #[ADAM, SGD, RMSprop]
  momentum: 0.9 #SGD momentum
  beta1: 0.9 #ADAM beta
  beta2: 0.999 #ADAM beta
  epsilon: 1e-8 #ADAM epsilon
  alpha: 0.9 #RMSprop alpha
  weight_dency: 0
  gclip: -1  #0.4  0.04  -1
  loss: MSE #[MSE, L1]
  use_YCbCr: False
  base_filter: 32
  in_w: 0.5
  grad_w: 1.5

