# python test.py --option_path=/home/amax/Documents/yxxxl/pansharpening/option_cunet.yml
# python test.py --option_path=/home/amax/Documents/yxxxl/pansharpening/option_dagf.yml
# python test.py --option_path=/home/amax/Documents/yxxxl/pansharpening/option_dkn.yml
# python test.py --option_path=/home/amax/Documents/yxxxl/pansharpening/option_fdkn.yml
# python test.py --option_path=/home/amax/Documents/yxxxl/pansharpening/option_pannet.yml
# python test.py --option_path=/home/amax/Documents/yxxxl/pansharpening/option_gppnn.yml
# python test.py --option_path=/home/amax/Documents/yxxxl/pansharpening/option_lacn.yml
# python test.py --option_path=/home/amax/Documents/yxxxl/pansharpening/option_fgf.yml
# python test.py --option_path=/home/amax/Documents/yxxxl/pansharpening/option_mmnet.yml
python mff_test.py --option_path /home/amax/Documents/yxxxl/pansharpening/option_mff_swinir.yml
# python test.py --option_path=/home/amax/Documents/yxxxl/pansharpening/option_svlrm.yml